// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scoreboard.Web.Datos;

#nullable disable

namespace Scoreboard.Web.Migrations
{
    [DbContext(typeof(ContextoMarcador))]
    [Migration("20251027010327_AddIsActiveToPlayLog")]
    partial class AddIsActiveToPlayLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Scoreboard.Web.Modelos.Entrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarrerasCasa")
                        .HasColumnType("int");

                    b.Property<int>("CarrerasVisita")
                        .HasColumnType("int");

                    b.Property<int>("ErroresCasa")
                        .HasColumnType("int");

                    b.Property<int>("ErroresVisita")
                        .HasColumnType("int");

                    b.Property<int>("HitsCasa")
                        .HasColumnType("int");

                    b.Property<int>("HitsVisita")
                        .HasColumnType("int");

                    b.Property<int>("NumeroInning")
                        .HasColumnType("int");

                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartidoId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("Scoreboard.Web.Modelos.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("Scoreboard.Web.Modelos.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int>("NumeroUniforme")
                        .HasColumnType("int");

                    b.Property<int>("Posicion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("Scoreboard.Web.Modelos.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("B1")
                        .HasColumnType("bit(1)");

                    b.Property<bool>("B2")
                        .HasColumnType("bit(1)");

                    b.Property<bool>("B3")
                        .HasColumnType("bit(1)");

                    b.Property<int>("CarrerasCasa")
                        .HasColumnType("int");

                    b.Property<int>("CarrerasVisita")
                        .HasColumnType("int");

                    b.Property<int>("EntradaActual")
                        .HasColumnType("int");

                    b.Property<int>("EquipoCasaId")
                        .HasColumnType("int");

                    b.Property<int>("EquipoVisitaId")
                        .HasColumnType("int");

                    b.Property<int>("ErroresCasa")
                        .HasColumnType("int");

                    b.Property<int>("ErroresVisita")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HitsCasa")
                        .HasColumnType("int");

                    b.Property<int>("HitsVisita")
                        .HasColumnType("int");

                    b.Property<int>("Mitad")
                        .HasColumnType("int");

                    b.Property<int>("Outs")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoCasaId");

                    b.HasIndex("EquipoVisitaId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("Scoreboard.Web.Modelos.PlayLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit(1)");

                    b.Property<int>("JugadorId")
                        .HasColumnType("int");

                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.Property<int>("Resultado")
                        .HasColumnType("int");

                    b.Property<int>("RunsScored")
                        .HasColumnType("int");

                    b.Property<string>("SnapshotJson")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PartidoId");

                    b.ToTable("PlayLogs");
                });

            modelBuilder.Entity("Scoreboard.Web.Modelos.PlayerBattingStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AB")
                        .HasColumnType("int");

                    b.Property<int>("BB")
                        .HasColumnType("int");

                    b.Property<int>("Doubles")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("H")
                        .HasColumnType("int");

                    b.Property<int>("HBP")
                        .HasColumnType("int");

                    b.Property<int>("HR")
                        .HasColumnType("int");

                    b.Property<int>("JugadorId")
                        .HasColumnType("int");

                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.Property<int>("R")
                        .HasColumnType("int");

                    b.Property<int>("RBI")
                        .HasColumnType("int");

                    b.Property<int>("SF")
                        .HasColumnType("int");

                    b.Property<int>("SO")
                        .HasColumnType("int");

                    b.Property<int>("Triples")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.ToTable("PlayerBattingStats");
                });

            modelBuilder.Entity("Scoreboard.Web.Modelos.Entrada", b =>
                {
                    b.HasOne("Scoreboard.Web.Modelos.Partido", "Partido")
                        .WithMany("Entradas")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("Scoreboard.Web.Modelos.Jugador", b =>
                {
                    b.HasOne("Scoreboard.Web.Modelos.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("Scoreboard.Web.Modelos.Partido", b =>
                {
                    b.HasOne("Scoreboard.Web.Modelos.Equipo", "EquipoCasa")
                        .WithMany()
                        .HasForeignKey("EquipoCasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Scoreboard.Web.Modelos.Equipo", "EquipoVisita")
                        .WithMany()
                        .HasForeignKey("EquipoVisitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipoCasa");

                    b.Navigation("EquipoVisita");
                });

            modelBuilder.Entity("Scoreboard.Web.Modelos.PlayLog", b =>
                {
                    b.HasOne("Scoreboard.Web.Modelos.Partido", "Partido")
                        .WithMany()
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("Scoreboard.Web.Modelos.PlayerBattingStat", b =>
                {
                    b.HasOne("Scoreboard.Web.Modelos.Jugador", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("Scoreboard.Web.Modelos.Partido", b =>
                {
                    b.Navigation("Entradas");
                });
#pragma warning restore 612, 618
        }
    }
}
