// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scoreboard.Web.Datos;

#nullable disable

namespace Scoreboard.Web.Migrations
{
    [DbContext(typeof(ContextoMarcador))]
    [Migration("20250907230828_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Scoreboard.Web.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("Scoreboard.Web.Models.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("Dorsal")
                        .HasColumnType("int");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId", "Dorsal");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("Scoreboard.Web.Models.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("B1")
                        .HasColumnType("bit(1)");

                    b.Property<bool>("B2")
                        .HasColumnType("bit(1)");

                    b.Property<bool>("B3")
                        .HasColumnType("bit(1)");

                    b.Property<int>("CarrerasCasa")
                        .HasColumnType("int");

                    b.Property<int>("CarrerasVisita")
                        .HasColumnType("int");

                    b.Property<int>("EntradaActual")
                        .HasColumnType("int");

                    b.Property<int>("EquipoCasaId")
                        .HasColumnType("int");

                    b.Property<int>("EquipoVisitaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Mitad")
                        .HasColumnType("int");

                    b.Property<int>("Outs")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoCasaId");

                    b.HasIndex("EquipoVisitaId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("Scoreboard.Web.Models.Jugador", b =>
                {
                    b.HasOne("Scoreboard.Web.Models.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("Scoreboard.Web.Models.Partido", b =>
                {
                    b.HasOne("Scoreboard.Web.Models.Equipo", "EquipoCasa")
                        .WithMany()
                        .HasForeignKey("EquipoCasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Scoreboard.Web.Models.Equipo", "EquipoVisita")
                        .WithMany()
                        .HasForeignKey("EquipoVisitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipoCasa");

                    b.Navigation("EquipoVisita");
                });
#pragma warning restore 612, 618
        }
    }
}
