// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Scoreboard.Web.Datos;

#nullable disable

namespace Scoreboard.Web.Migrations
{
    [DbContext(typeof(ContextoMarcador))]
    [Migration("20260429225500_AddMissingPlayLogKind")]
    partial class AddMissingPlayLogKind
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);
#pragma warning restore 612, 618
        }
    }
}
